name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Alishba-Alvi
          template: classic
          base: "header, activity"
